//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model1", "GameAtBat", "Game", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PitchFX.DAL.Game), "AtBat", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PitchFX.DAL.AtBat), true)]
[assembly: EdmRelationshipAttribute("Model1", "AtBatPitch", "AtBat", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PitchFX.DAL.AtBat), "Pitch", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PitchFX.DAL.Pitch), true)]

#endregion

namespace PitchFX.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model1Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model1Container object using the connection string found in the 'Model1Container' section of the application configuration file.
        /// </summary>
        public Model1Container() : base("name=Model1Container", "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(string connectionString) : base(connectionString, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(EntityConnection connection) : base(connection, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AtBat> AtBats
        {
            get
            {
                if ((_AtBats == null))
                {
                    _AtBats = base.CreateObjectSet<AtBat>("AtBats");
                }
                return _AtBats;
            }
        }
        private ObjectSet<AtBat> _AtBats;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Game> Games
        {
            get
            {
                if ((_Games == null))
                {
                    _Games = base.CreateObjectSet<Game>("Games");
                }
                return _Games;
            }
        }
        private ObjectSet<Game> _Games;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pitch> Pitches
        {
            get
            {
                if ((_Pitches == null))
                {
                    _Pitches = base.CreateObjectSet<Pitch>("Pitches");
                }
                return _Pitches;
            }
        }
        private ObjectSet<Pitch> _Pitches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Player> Players
        {
            get
            {
                if ((_Players == null))
                {
                    _Players = base.CreateObjectSet<Player>("Players");
                }
                return _Players;
            }
        }
        private ObjectSet<Player> _Players;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AtBats EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAtBats(AtBat atBat)
        {
            base.AddObject("AtBats", atBat);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Games EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGames(Game game)
        {
            base.AddObject("Games", game);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pitches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPitches(Pitch pitch)
        {
            base.AddObject("Pitches", pitch);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Players EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPlayers(Player player)
        {
            base.AddObject("Players", player);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="AtBat")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AtBat : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AtBat object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="strikes">Initial value of the Strikes property.</param>
        /// <param name="balls">Initial value of the Balls property.</param>
        /// <param name="outs">Initial value of the Outs property.</param>
        /// <param name="batter">Initial value of the batter property.</param>
        /// <param name="stand">Initial value of the stand property.</param>
        /// <param name="pitcher">Initial value of the pitcher property.</param>
        /// <param name="atbat_des">Initial value of the atbat_des property.</param>
        /// <param name="atbat_event">Initial value of the atbat_event property.</param>
        /// <param name="inning">Initial value of the Inning property.</param>
        /// <param name="atbat_num">Initial value of the atbat_num property.</param>
        /// <param name="gameId">Initial value of the GameId property.</param>
        /// <param name="inningHalf">Initial value of the InningHalf property.</param>
        public static AtBat CreateAtBat(global::System.Int32 id, global::System.Int16 strikes, global::System.Int16 balls, global::System.Int16 outs, global::System.Int32 batter, global::System.String stand, global::System.Int32 pitcher, global::System.String atbat_des, global::System.String atbat_event, global::System.Int16 inning, global::System.Int16 atbat_num, global::System.Int32 gameId, global::System.String inningHalf)
        {
            AtBat atBat = new AtBat();
            atBat.Id = id;
            atBat.Strikes = strikes;
            atBat.Balls = balls;
            atBat.Outs = outs;
            atBat.batter = batter;
            atBat.stand = stand;
            atBat.pitcher = pitcher;
            atBat.atbat_des = atbat_des;
            atBat.atbat_event = atbat_event;
            atBat.Inning = inning;
            atBat.atbat_num = atbat_num;
            atBat.GameId = gameId;
            atBat.InningHalf = inningHalf;
            return atBat;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Strikes
        {
            get
            {
                return _Strikes;
            }
            set
            {
                OnStrikesChanging(value);
                ReportPropertyChanging("Strikes");
                _Strikes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Strikes");
                OnStrikesChanged();
            }
        }
        private global::System.Int16 _Strikes;
        partial void OnStrikesChanging(global::System.Int16 value);
        partial void OnStrikesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Balls
        {
            get
            {
                return _Balls;
            }
            set
            {
                OnBallsChanging(value);
                ReportPropertyChanging("Balls");
                _Balls = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Balls");
                OnBallsChanged();
            }
        }
        private global::System.Int16 _Balls;
        partial void OnBallsChanging(global::System.Int16 value);
        partial void OnBallsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Outs
        {
            get
            {
                return _Outs;
            }
            set
            {
                OnOutsChanging(value);
                ReportPropertyChanging("Outs");
                _Outs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Outs");
                OnOutsChanged();
            }
        }
        private global::System.Int16 _Outs;
        partial void OnOutsChanging(global::System.Int16 value);
        partial void OnOutsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String start_tfs
        {
            get
            {
                return _start_tfs;
            }
            set
            {
                Onstart_tfsChanging(value);
                ReportPropertyChanging("start_tfs");
                _start_tfs = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("start_tfs");
                Onstart_tfsChanged();
            }
        }
        private global::System.String _start_tfs;
        partial void Onstart_tfsChanging(global::System.String value);
        partial void Onstart_tfsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String start_tfs_zulu
        {
            get
            {
                return _start_tfs_zulu;
            }
            set
            {
                Onstart_tfs_zuluChanging(value);
                ReportPropertyChanging("start_tfs_zulu");
                _start_tfs_zulu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("start_tfs_zulu");
                Onstart_tfs_zuluChanged();
            }
        }
        private global::System.String _start_tfs_zulu;
        partial void Onstart_tfs_zuluChanging(global::System.String value);
        partial void Onstart_tfs_zuluChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 batter
        {
            get
            {
                return _batter;
            }
            set
            {
                OnbatterChanging(value);
                ReportPropertyChanging("batter");
                _batter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("batter");
                OnbatterChanged();
            }
        }
        private global::System.Int32 _batter;
        partial void OnbatterChanging(global::System.Int32 value);
        partial void OnbatterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String stand
        {
            get
            {
                return _stand;
            }
            set
            {
                OnstandChanging(value);
                ReportPropertyChanging("stand");
                _stand = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("stand");
                OnstandChanged();
            }
        }
        private global::System.String _stand;
        partial void OnstandChanging(global::System.String value);
        partial void OnstandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String b_height
        {
            get
            {
                return _b_height;
            }
            set
            {
                Onb_heightChanging(value);
                ReportPropertyChanging("b_height");
                _b_height = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("b_height");
                Onb_heightChanged();
            }
        }
        private global::System.String _b_height;
        partial void Onb_heightChanging(global::System.String value);
        partial void Onb_heightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pitcher
        {
            get
            {
                return _pitcher;
            }
            set
            {
                OnpitcherChanging(value);
                ReportPropertyChanging("pitcher");
                _pitcher = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pitcher");
                OnpitcherChanged();
            }
        }
        private global::System.Int32 _pitcher;
        partial void OnpitcherChanging(global::System.Int32 value);
        partial void OnpitcherChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String p_throws
        {
            get
            {
                return _p_throws;
            }
            set
            {
                Onp_throwsChanging(value);
                ReportPropertyChanging("p_throws");
                _p_throws = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("p_throws");
                Onp_throwsChanged();
            }
        }
        private global::System.String _p_throws;
        partial void Onp_throwsChanging(global::System.String value);
        partial void Onp_throwsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String atbat_des
        {
            get
            {
                return _atbat_des;
            }
            set
            {
                Onatbat_desChanging(value);
                ReportPropertyChanging("atbat_des");
                _atbat_des = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("atbat_des");
                Onatbat_desChanged();
            }
        }
        private global::System.String _atbat_des;
        partial void Onatbat_desChanging(global::System.String value);
        partial void Onatbat_desChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String atbat_event
        {
            get
            {
                return _atbat_event;
            }
            set
            {
                Onatbat_eventChanging(value);
                ReportPropertyChanging("atbat_event");
                _atbat_event = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("atbat_event");
                Onatbat_eventChanged();
            }
        }
        private global::System.String _atbat_event;
        partial void Onatbat_eventChanging(global::System.String value);
        partial void Onatbat_eventChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Inning
        {
            get
            {
                return _Inning;
            }
            set
            {
                OnInningChanging(value);
                ReportPropertyChanging("Inning");
                _Inning = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Inning");
                OnInningChanged();
            }
        }
        private global::System.Int16 _Inning;
        partial void OnInningChanging(global::System.Int16 value);
        partial void OnInningChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 atbat_num
        {
            get
            {
                return _atbat_num;
            }
            set
            {
                Onatbat_numChanging(value);
                ReportPropertyChanging("atbat_num");
                _atbat_num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("atbat_num");
                Onatbat_numChanged();
            }
        }
        private global::System.Int16 _atbat_num;
        partial void Onatbat_numChanging(global::System.Int16 value);
        partial void Onatbat_numChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GameId
        {
            get
            {
                return _GameId;
            }
            set
            {
                OnGameIdChanging(value);
                ReportPropertyChanging("GameId");
                _GameId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GameId");
                OnGameIdChanged();
            }
        }
        private global::System.Int32 _GameId;
        partial void OnGameIdChanging(global::System.Int32 value);
        partial void OnGameIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InningHalf
        {
            get
            {
                return _InningHalf;
            }
            set
            {
                OnInningHalfChanging(value);
                ReportPropertyChanging("InningHalf");
                _InningHalf = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("InningHalf");
                OnInningHalfChanged();
            }
        }
        private global::System.String _InningHalf;
        partial void OnInningHalfChanging(global::System.String value);
        partial void OnInningHalfChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> play_guid
        {
            get
            {
                return _play_guid;
            }
            set
            {
                Onplay_guidChanging(value);
                ReportPropertyChanging("play_guid");
                _play_guid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("play_guid");
                Onplay_guidChanged();
            }
        }
        private Nullable<global::System.Guid> _play_guid;
        partial void Onplay_guidChanging(Nullable<global::System.Guid> value);
        partial void Onplay_guidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GID
        {
            get
            {
                return _GID;
            }
            set
            {
                OnGIDChanging(value);
                ReportPropertyChanging("GID");
                _GID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GID");
                OnGIDChanged();
            }
        }
        private global::System.String _GID;
        partial void OnGIDChanging(global::System.String value);
        partial void OnGIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "GameAtBat", "Game")]
        public Game Game
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Game>("Model1.GameAtBat", "Game").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Game>("Model1.GameAtBat", "Game").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Game> GameReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Game>("Model1.GameAtBat", "Game");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Game>("Model1.GameAtBat", "Game", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "AtBatPitch", "Pitch")]
        public EntityCollection<Pitch> Pitches
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pitch>("Model1.AtBatPitch", "Pitch");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pitch>("Model1.AtBatPitch", "Pitch", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Game")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Game : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Game object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="gameDate">Initial value of the GameDate property.</param>
        public static Game CreateGame(global::System.Int32 id, global::System.String description, global::System.DateTime gameDate)
        {
            Game game = new Game();
            game.Id = id;
            game.Description = description;
            game.GameDate = gameDate;
            return game;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime GameDate
        {
            get
            {
                return _GameDate;
            }
            set
            {
                OnGameDateChanging(value);
                ReportPropertyChanging("GameDate");
                _GameDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GameDate");
                OnGameDateChanged();
            }
        }
        private global::System.DateTime _GameDate;
        partial void OnGameDateChanging(global::System.DateTime value);
        partial void OnGameDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomeTeam
        {
            get
            {
                return _HomeTeam;
            }
            set
            {
                OnHomeTeamChanging(value);
                ReportPropertyChanging("HomeTeam");
                _HomeTeam = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomeTeam");
                OnHomeTeamChanged();
            }
        }
        private global::System.String _HomeTeam;
        partial void OnHomeTeamChanging(global::System.String value);
        partial void OnHomeTeamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AwayTeam
        {
            get
            {
                return _AwayTeam;
            }
            set
            {
                OnAwayTeamChanging(value);
                ReportPropertyChanging("AwayTeam");
                _AwayTeam = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AwayTeam");
                OnAwayTeamChanged();
            }
        }
        private global::System.String _AwayTeam;
        partial void OnAwayTeamChanging(global::System.String value);
        partial void OnAwayTeamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GID
        {
            get
            {
                return _GID;
            }
            set
            {
                OnGIDChanging(value);
                ReportPropertyChanging("GID");
                _GID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GID");
                OnGIDChanged();
            }
        }
        private global::System.String _GID;
        partial void OnGIDChanging(global::System.String value);
        partial void OnGIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "GameAtBat", "AtBat")]
        public EntityCollection<AtBat> AtBats
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AtBat>("Model1.GameAtBat", "AtBat");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AtBat>("Model1.GameAtBat", "AtBat", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Pitch")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pitch : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pitch object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="des">Initial value of the des property.</param>
        /// <param name="pitch_id">Initial value of the pitch_id property.</param>
        /// <param name="atBatId">Initial value of the AtBatId property.</param>
        public static Pitch CreatePitch(global::System.Int32 id, global::System.String des, global::System.Int32 pitch_id, global::System.Int32 atBatId)
        {
            Pitch pitch = new Pitch();
            pitch.Id = id;
            pitch.des = des;
            pitch.pitch_id = pitch_id;
            pitch.AtBatId = atBatId;
            return pitch;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String des
        {
            get
            {
                return _des;
            }
            set
            {
                OndesChanging(value);
                ReportPropertyChanging("des");
                _des = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("des");
                OndesChanged();
            }
        }
        private global::System.String _des;
        partial void OndesChanging(global::System.String value);
        partial void OndesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 pitch_id
        {
            get
            {
                return _pitch_id;
            }
            set
            {
                Onpitch_idChanging(value);
                ReportPropertyChanging("pitch_id");
                _pitch_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pitch_id");
                Onpitch_idChanged();
            }
        }
        private global::System.Int32 _pitch_id;
        partial void Onpitch_idChanging(global::System.Int32 value);
        partial void Onpitch_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tfs
        {
            get
            {
                return _tfs;
            }
            set
            {
                OntfsChanging(value);
                ReportPropertyChanging("tfs");
                _tfs = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tfs");
                OntfsChanged();
            }
        }
        private global::System.String _tfs;
        partial void OntfsChanging(global::System.String value);
        partial void OntfsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tfs_zulu
        {
            get
            {
                return _tfs_zulu;
            }
            set
            {
                Ontfs_zuluChanging(value);
                ReportPropertyChanging("tfs_zulu");
                _tfs_zulu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tfs_zulu");
                Ontfs_zuluChanged();
            }
        }
        private global::System.String _tfs_zulu;
        partial void Ontfs_zuluChanging(global::System.String value);
        partial void Ontfs_zuluChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> x
        {
            get
            {
                return _x;
            }
            set
            {
                OnxChanging(value);
                ReportPropertyChanging("x");
                _x = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("x");
                OnxChanged();
            }
        }
        private Nullable<global::System.Decimal> _x;
        partial void OnxChanging(Nullable<global::System.Decimal> value);
        partial void OnxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> y
        {
            get
            {
                return _y;
            }
            set
            {
                OnyChanging(value);
                ReportPropertyChanging("y");
                _y = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("y");
                OnyChanged();
            }
        }
        private Nullable<global::System.Decimal> _y;
        partial void OnyChanging(Nullable<global::System.Decimal> value);
        partial void OnyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sv_id
        {
            get
            {
                return _sv_id;
            }
            set
            {
                Onsv_idChanging(value);
                ReportPropertyChanging("sv_id");
                _sv_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sv_id");
                Onsv_idChanged();
            }
        }
        private global::System.String _sv_id;
        partial void Onsv_idChanging(global::System.String value);
        partial void Onsv_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> start_speed
        {
            get
            {
                return _start_speed;
            }
            set
            {
                Onstart_speedChanging(value);
                ReportPropertyChanging("start_speed");
                _start_speed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_speed");
                Onstart_speedChanged();
            }
        }
        private Nullable<global::System.Decimal> _start_speed;
        partial void Onstart_speedChanging(Nullable<global::System.Decimal> value);
        partial void Onstart_speedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> end_speed
        {
            get
            {
                return _end_speed;
            }
            set
            {
                Onend_speedChanging(value);
                ReportPropertyChanging("end_speed");
                _end_speed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("end_speed");
                Onend_speedChanged();
            }
        }
        private Nullable<global::System.Decimal> _end_speed;
        partial void Onend_speedChanging(Nullable<global::System.Decimal> value);
        partial void Onend_speedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> sz_top
        {
            get
            {
                return _sz_top;
            }
            set
            {
                Onsz_topChanging(value);
                ReportPropertyChanging("sz_top");
                _sz_top = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sz_top");
                Onsz_topChanged();
            }
        }
        private Nullable<global::System.Decimal> _sz_top;
        partial void Onsz_topChanging(Nullable<global::System.Decimal> value);
        partial void Onsz_topChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> sz_bot
        {
            get
            {
                return _sz_bot;
            }
            set
            {
                Onsz_botChanging(value);
                ReportPropertyChanging("sz_bot");
                _sz_bot = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sz_bot");
                Onsz_botChanged();
            }
        }
        private Nullable<global::System.Decimal> _sz_bot;
        partial void Onsz_botChanging(Nullable<global::System.Decimal> value);
        partial void Onsz_botChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> pfx_x
        {
            get
            {
                return _pfx_x;
            }
            set
            {
                Onpfx_xChanging(value);
                ReportPropertyChanging("pfx_x");
                _pfx_x = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pfx_x");
                Onpfx_xChanged();
            }
        }
        private Nullable<global::System.Decimal> _pfx_x;
        partial void Onpfx_xChanging(Nullable<global::System.Decimal> value);
        partial void Onpfx_xChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> pfx_z
        {
            get
            {
                return _pfx_z;
            }
            set
            {
                Onpfx_zChanging(value);
                ReportPropertyChanging("pfx_z");
                _pfx_z = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pfx_z");
                Onpfx_zChanged();
            }
        }
        private Nullable<global::System.Decimal> _pfx_z;
        partial void Onpfx_zChanging(Nullable<global::System.Decimal> value);
        partial void Onpfx_zChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> px
        {
            get
            {
                return _px;
            }
            set
            {
                OnpxChanging(value);
                ReportPropertyChanging("px");
                _px = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("px");
                OnpxChanged();
            }
        }
        private Nullable<global::System.Decimal> _px;
        partial void OnpxChanging(Nullable<global::System.Decimal> value);
        partial void OnpxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> pz
        {
            get
            {
                return _pz;
            }
            set
            {
                OnpzChanging(value);
                ReportPropertyChanging("pz");
                _pz = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("pz");
                OnpzChanged();
            }
        }
        private Nullable<global::System.Decimal> _pz;
        partial void OnpzChanging(Nullable<global::System.Decimal> value);
        partial void OnpzChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> x0
        {
            get
            {
                return _x0;
            }
            set
            {
                Onx0Changing(value);
                ReportPropertyChanging("x0");
                _x0 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("x0");
                Onx0Changed();
            }
        }
        private Nullable<global::System.Decimal> _x0;
        partial void Onx0Changing(Nullable<global::System.Decimal> value);
        partial void Onx0Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> y0
        {
            get
            {
                return _y0;
            }
            set
            {
                Ony0Changing(value);
                ReportPropertyChanging("y0");
                _y0 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("y0");
                Ony0Changed();
            }
        }
        private Nullable<global::System.Decimal> _y0;
        partial void Ony0Changing(Nullable<global::System.Decimal> value);
        partial void Ony0Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> z0
        {
            get
            {
                return _z0;
            }
            set
            {
                Onz0Changing(value);
                ReportPropertyChanging("z0");
                _z0 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("z0");
                Onz0Changed();
            }
        }
        private Nullable<global::System.Decimal> _z0;
        partial void Onz0Changing(Nullable<global::System.Decimal> value);
        partial void Onz0Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> vx0
        {
            get
            {
                return _vx0;
            }
            set
            {
                Onvx0Changing(value);
                ReportPropertyChanging("vx0");
                _vx0 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vx0");
                Onvx0Changed();
            }
        }
        private Nullable<global::System.Decimal> _vx0;
        partial void Onvx0Changing(Nullable<global::System.Decimal> value);
        partial void Onvx0Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> vy0
        {
            get
            {
                return _vy0;
            }
            set
            {
                Onvy0Changing(value);
                ReportPropertyChanging("vy0");
                _vy0 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vy0");
                Onvy0Changed();
            }
        }
        private Nullable<global::System.Decimal> _vy0;
        partial void Onvy0Changing(Nullable<global::System.Decimal> value);
        partial void Onvy0Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> vz0
        {
            get
            {
                return _vz0;
            }
            set
            {
                Onvz0Changing(value);
                ReportPropertyChanging("vz0");
                _vz0 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vz0");
                Onvz0Changed();
            }
        }
        private Nullable<global::System.Decimal> _vz0;
        partial void Onvz0Changing(Nullable<global::System.Decimal> value);
        partial void Onvz0Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ax
        {
            get
            {
                return _ax;
            }
            set
            {
                OnaxChanging(value);
                ReportPropertyChanging("ax");
                _ax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ax");
                OnaxChanged();
            }
        }
        private Nullable<global::System.Decimal> _ax;
        partial void OnaxChanging(Nullable<global::System.Decimal> value);
        partial void OnaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ay
        {
            get
            {
                return _ay;
            }
            set
            {
                OnayChanging(value);
                ReportPropertyChanging("ay");
                _ay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ay");
                OnayChanged();
            }
        }
        private Nullable<global::System.Decimal> _ay;
        partial void OnayChanging(Nullable<global::System.Decimal> value);
        partial void OnayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> az
        {
            get
            {
                return _az;
            }
            set
            {
                OnazChanging(value);
                ReportPropertyChanging("az");
                _az = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("az");
                OnazChanged();
            }
        }
        private Nullable<global::System.Decimal> _az;
        partial void OnazChanging(Nullable<global::System.Decimal> value);
        partial void OnazChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> break_y
        {
            get
            {
                return _break_y;
            }
            set
            {
                Onbreak_yChanging(value);
                ReportPropertyChanging("break_y");
                _break_y = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("break_y");
                Onbreak_yChanged();
            }
        }
        private Nullable<global::System.Decimal> _break_y;
        partial void Onbreak_yChanging(Nullable<global::System.Decimal> value);
        partial void Onbreak_yChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> break_angle
        {
            get
            {
                return _break_angle;
            }
            set
            {
                Onbreak_angleChanging(value);
                ReportPropertyChanging("break_angle");
                _break_angle = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("break_angle");
                Onbreak_angleChanged();
            }
        }
        private Nullable<global::System.Decimal> _break_angle;
        partial void Onbreak_angleChanging(Nullable<global::System.Decimal> value);
        partial void Onbreak_angleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> break_length
        {
            get
            {
                return _break_length;
            }
            set
            {
                Onbreak_lengthChanging(value);
                ReportPropertyChanging("break_length");
                _break_length = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("break_length");
                Onbreak_lengthChanged();
            }
        }
        private Nullable<global::System.Decimal> _break_length;
        partial void Onbreak_lengthChanging(Nullable<global::System.Decimal> value);
        partial void Onbreak_lengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pitch_type
        {
            get
            {
                return _pitch_type;
            }
            set
            {
                Onpitch_typeChanging(value);
                ReportPropertyChanging("pitch_type");
                _pitch_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pitch_type");
                Onpitch_typeChanged();
            }
        }
        private global::System.String _pitch_type;
        partial void Onpitch_typeChanging(global::System.String value);
        partial void Onpitch_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> type_confidence
        {
            get
            {
                return _type_confidence;
            }
            set
            {
                Ontype_confidenceChanging(value);
                ReportPropertyChanging("type_confidence");
                _type_confidence = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("type_confidence");
                Ontype_confidenceChanged();
            }
        }
        private Nullable<global::System.Decimal> _type_confidence;
        partial void Ontype_confidenceChanging(Nullable<global::System.Decimal> value);
        partial void Ontype_confidenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> zone
        {
            get
            {
                return _zone;
            }
            set
            {
                OnzoneChanging(value);
                ReportPropertyChanging("zone");
                _zone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("zone");
                OnzoneChanged();
            }
        }
        private Nullable<global::System.Int32> _zone;
        partial void OnzoneChanging(Nullable<global::System.Int32> value);
        partial void OnzoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nasty
        {
            get
            {
                return _nasty;
            }
            set
            {
                OnnastyChanging(value);
                ReportPropertyChanging("nasty");
                _nasty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nasty");
                OnnastyChanged();
            }
        }
        private Nullable<global::System.Int32> _nasty;
        partial void OnnastyChanging(Nullable<global::System.Int32> value);
        partial void OnnastyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> spin_dir
        {
            get
            {
                return _spin_dir;
            }
            set
            {
                Onspin_dirChanging(value);
                ReportPropertyChanging("spin_dir");
                _spin_dir = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("spin_dir");
                Onspin_dirChanged();
            }
        }
        private Nullable<global::System.Decimal> _spin_dir;
        partial void Onspin_dirChanging(Nullable<global::System.Decimal> value);
        partial void Onspin_dirChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> spin_rate
        {
            get
            {
                return _spin_rate;
            }
            set
            {
                Onspin_rateChanging(value);
                ReportPropertyChanging("spin_rate");
                _spin_rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("spin_rate");
                Onspin_rateChanged();
            }
        }
        private Nullable<global::System.Decimal> _spin_rate;
        partial void Onspin_rateChanging(Nullable<global::System.Decimal> value);
        partial void Onspin_rateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cc
        {
            get
            {
                return _cc;
            }
            set
            {
                OnccChanging(value);
                ReportPropertyChanging("cc");
                _cc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cc");
                OnccChanged();
            }
        }
        private global::System.String _cc;
        partial void OnccChanging(global::System.String value);
        partial void OnccChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mt
        {
            get
            {
                return _mt;
            }
            set
            {
                OnmtChanging(value);
                ReportPropertyChanging("mt");
                _mt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mt");
                OnmtChanged();
            }
        }
        private global::System.String _mt;
        partial void OnmtChanging(global::System.String value);
        partial void OnmtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AtBatId
        {
            get
            {
                return _AtBatId;
            }
            set
            {
                OnAtBatIdChanging(value);
                ReportPropertyChanging("AtBatId");
                _AtBatId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AtBatId");
                OnAtBatIdChanged();
            }
        }
        private global::System.Int32 _AtBatId;
        partial void OnAtBatIdChanging(global::System.Int32 value);
        partial void OnAtBatIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> play_guid
        {
            get
            {
                return _play_guid;
            }
            set
            {
                Onplay_guidChanging(value);
                ReportPropertyChanging("play_guid");
                _play_guid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("play_guid");
                Onplay_guidChanged();
            }
        }
        private Nullable<global::System.Guid> _play_guid;
        partial void Onplay_guidChanging(Nullable<global::System.Guid> value);
        partial void Onplay_guidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GID
        {
            get
            {
                return _GID;
            }
            set
            {
                OnGIDChanging(value);
                ReportPropertyChanging("GID");
                _GID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GID");
                OnGIDChanged();
            }
        }
        private global::System.String _GID;
        partial void OnGIDChanging(global::System.String value);
        partial void OnGIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "AtBatPitch", "AtBat")]
        public AtBat AtBat
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AtBat>("Model1.AtBatPitch", "AtBat").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AtBat>("Model1.AtBatPitch", "AtBat").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AtBat> AtBatReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AtBat>("Model1.AtBatPitch", "AtBat");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AtBat>("Model1.AtBatPitch", "AtBat", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Player")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Player : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Player object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="first">Initial value of the first property.</param>
        /// <param name="last">Initial value of the last property.</param>
        /// <param name="row_id">Initial value of the row_id property.</param>
        public static Player CreatePlayer(global::System.Int32 id, global::System.String first, global::System.String last, global::System.Int32 row_id)
        {
            Player player = new Player();
            player.id = id;
            player.first = first;
            player.last = last;
            player.row_id = row_id;
            return player;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String first
        {
            get
            {
                return _first;
            }
            set
            {
                OnfirstChanging(value);
                ReportPropertyChanging("first");
                _first = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("first");
                OnfirstChanged();
            }
        }
        private global::System.String _first;
        partial void OnfirstChanging(global::System.String value);
        partial void OnfirstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String last
        {
            get
            {
                return _last;
            }
            set
            {
                OnlastChanging(value);
                ReportPropertyChanging("last");
                _last = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("last");
                OnlastChanged();
            }
        }
        private global::System.String _last;
        partial void OnlastChanging(global::System.String value);
        partial void OnlastChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> num
        {
            get
            {
                return _num;
            }
            set
            {
                OnnumChanging(value);
                ReportPropertyChanging("num");
                _num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num");
                OnnumChanged();
            }
        }
        private Nullable<global::System.Int32> _num;
        partial void OnnumChanging(Nullable<global::System.Int32> value);
        partial void OnnumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String boxname
        {
            get
            {
                return _boxname;
            }
            set
            {
                OnboxnameChanging(value);
                ReportPropertyChanging("boxname");
                _boxname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("boxname");
                OnboxnameChanged();
            }
        }
        private global::System.String _boxname;
        partial void OnboxnameChanging(global::System.String value);
        partial void OnboxnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rl
        {
            get
            {
                return _rl;
            }
            set
            {
                OnrlChanging(value);
                ReportPropertyChanging("rl");
                _rl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rl");
                OnrlChanged();
            }
        }
        private global::System.String _rl;
        partial void OnrlChanging(global::System.String value);
        partial void OnrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String position
        {
            get
            {
                return _position;
            }
            set
            {
                OnpositionChanging(value);
                ReportPropertyChanging("position");
                _position = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("position");
                OnpositionChanged();
            }
        }
        private global::System.String _position;
        partial void OnpositionChanging(global::System.String value);
        partial void OnpositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bat_order
        {
            get
            {
                return _bat_order;
            }
            set
            {
                Onbat_orderChanging(value);
                ReportPropertyChanging("bat_order");
                _bat_order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bat_order");
                Onbat_orderChanged();
            }
        }
        private Nullable<global::System.Int32> _bat_order;
        partial void Onbat_orderChanging(Nullable<global::System.Int32> value);
        partial void Onbat_orderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String game_position
        {
            get
            {
                return _game_position;
            }
            set
            {
                Ongame_positionChanging(value);
                ReportPropertyChanging("game_position");
                _game_position = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("game_position");
                Ongame_positionChanged();
            }
        }
        private global::System.String _game_position;
        partial void Ongame_positionChanging(global::System.String value);
        partial void Ongame_positionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> avg
        {
            get
            {
                return _avg;
            }
            set
            {
                OnavgChanging(value);
                ReportPropertyChanging("avg");
                _avg = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("avg");
                OnavgChanged();
            }
        }
        private Nullable<global::System.Decimal> _avg;
        partial void OnavgChanging(Nullable<global::System.Decimal> value);
        partial void OnavgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> hr
        {
            get
            {
                return _hr;
            }
            set
            {
                OnhrChanging(value);
                ReportPropertyChanging("hr");
                _hr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hr");
                OnhrChanged();
            }
        }
        private Nullable<global::System.Int32> _hr;
        partial void OnhrChanging(Nullable<global::System.Int32> value);
        partial void OnhrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> rbi
        {
            get
            {
                return _rbi;
            }
            set
            {
                OnrbiChanging(value);
                ReportPropertyChanging("rbi");
                _rbi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rbi");
                OnrbiChanged();
            }
        }
        private Nullable<global::System.Int32> _rbi;
        partial void OnrbiChanging(Nullable<global::System.Int32> value);
        partial void OnrbiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> wins
        {
            get
            {
                return _wins;
            }
            set
            {
                OnwinsChanging(value);
                ReportPropertyChanging("wins");
                _wins = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("wins");
                OnwinsChanged();
            }
        }
        private Nullable<global::System.Int32> _wins;
        partial void OnwinsChanging(Nullable<global::System.Int32> value);
        partial void OnwinsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> losses
        {
            get
            {
                return _losses;
            }
            set
            {
                OnlossesChanging(value);
                ReportPropertyChanging("losses");
                _losses = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("losses");
                OnlossesChanged();
            }
        }
        private Nullable<global::System.Int32> _losses;
        partial void OnlossesChanging(Nullable<global::System.Int32> value);
        partial void OnlossesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> era
        {
            get
            {
                return _era;
            }
            set
            {
                OneraChanging(value);
                ReportPropertyChanging("era");
                _era = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("era");
                OneraChanged();
            }
        }
        private Nullable<global::System.Decimal> _era;
        partial void OneraChanging(Nullable<global::System.Decimal> value);
        partial void OneraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GID
        {
            get
            {
                return _GID;
            }
            set
            {
                OnGIDChanging(value);
                ReportPropertyChanging("GID");
                _GID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GID");
                OnGIDChanged();
            }
        }
        private global::System.String _GID;
        partial void OnGIDChanging(global::System.String value);
        partial void OnGIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 row_id
        {
            get
            {
                return _row_id;
            }
            set
            {
                if (_row_id != value)
                {
                    Onrow_idChanging(value);
                    ReportPropertyChanging("row_id");
                    _row_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("row_id");
                    Onrow_idChanged();
                }
            }
        }
        private global::System.Int32 _row_id;
        partial void Onrow_idChanging(global::System.Int32 value);
        partial void Onrow_idChanged();

        #endregion

    
    }

    #endregion

    
}
